version: '2.0'
services: 
  backend:
    build: .
    image: leonid97/cisco_backend:latest
    ports:
      - "8081:8081"
    depends_on: 
      - "mongo"
  mongo:
    image: "mongo"
    ports: 
      - "27017:27017"
  